podName: backblaze-runner
appLabel: backblaze-runner
containerName: backblaze-runner
image: jpyles/backblaze-runner:latest

{{- $config := .Files.Get "../../config.yaml" | fromYaml -}}
backups: {{ $config.backups | toYaml | nindent 2 }}